# Generated by Django 4.0.6 on 2022-08-02 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('location', models.TextField()),
                ('dustbinHeight', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('lastFullTime', models.DateTimeField(blank=True, null=True)),
                ('lastCleanTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('height', models.FloatField()),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('gas', models.FloatField()),
                ('unwanted_gas', models.BooleanField(default=False)),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
