# Generated by Django 4.1 on 2022-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
