# Generated by Django 4.1 on 2022-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
